<?php

namespace App;

use App\Scopes\SellerScope;
use App\Transformers\SellerTransformer;
use Illuminate\Database\Eloquent\Model;


class Seller extends User
{
    public $transformer=SellerTransformer::class;
    //adding SellerScop
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new SellerScope());
    }

    //One To Many Relationship
    public function products(){
        return $this->hasMany('App\Product');
    }
}
